resilience4j:  circuitbreaker:    configs:      defecto:        sliding-window-size: 6        failure-rate-threshold: 50        wait-duration-in-open-state: 20s        permitted-number-of-calls-in-half-open-state: 4        slow-call-rate-threshold: 50        slow-call-duration-threshold: 2s    instances:      productos:        base-config: defecto  timelimiter:    configs:      defecto:        timeout-duration: 2s    instances:      productos:        base-config: defectoserver:  port: 8090eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: servicio-gateway-server
  cloud: 
    gateway: 
      routes: 
      - id: productos-service
        uri: lb://productos-service
        predicates: 
          - Path= /productos/**
        filters:           - name: CircuitBreaker            args:              name: productos               statusCodes: 500               fallbackUri: forward:/items/ver/9/cantidad/5          - StripPrefix=1          - Ejemplo=mensaje_filtro, nombre_usuario
      - id: productos-client
        uri: lb://productos-client
        predicates: 
          - Path= /items/**
        filters: 
          - StripPrefix=1          - name: Ejemplo            args:              mensaje: mensaje_xd              usuario: un_user_xs